# -*- coding: utf-8 -*-
"""Download YT Playlist to MP4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RKHXp_zJKwuVyveQnzOorYDY36W8B5bR
"""

!pip install pytube

import os
import subprocess

from pytube import Playlist, YouTube


def download_playlist(playlist_url):
    # Use the current working directory as the default directory for saving files
    default_directory = os.getcwd()

    # Create a playlist object from the provided URL
    playlist = Playlist(playlist_url)

    # Iterate over the videos in the playlist
    for video_url in playlist.video_urls:
        # Create a YouTube object from the video URL
        video = YouTube(video_url)

        # Select the first stream, since it will be converted to mp4 anyway
        stream = video.streams.first()

        # Get the default filename for the selected stream
        default_filename = stream.default_filename
        print(f"Downloading '{default_filename}'...")

        # Download the stream to the default directory
        stream.download(output_path=default_directory)

        # Create a new filename for the downloaded file with an mp4 extension
        new_filename = os.path.splitext(default_filename)[0] + ".mp4"

        # Convert the downloaded file to mp4 using ffmpeg
        print(f"Converting '{default_filename}' to mp4...")
        subprocess.run(['ffmpeg', '-i', 
            os.path.join(default_directory, default_filename),
            '-f', 'mp4',
            os.path.join(default_directory, new_filename)
        ])

    print("Download complete!")


if __name__ == "__main__":
    # Prompt the user for a playlist URL
    playlist_url = input("Please enter the URL of the playlist you wish to download: ")
    download_playlist(playlist_url)